### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Vastxiao** [howie6879/ruia#111]
hi， 大佬您好，看到这个框架，经过仔细研究了下发现真的是很好用，其中也研读理解了部分源码，受益良多啊，是很个棒的框架。但是在使用中还是出现了这样的问题：

如果在一个 loop里同时运行两个以上的 Spider 实例(这里是使用的 Spider.async_start())这个方法运行，例如这样:

```python
class SpiderA(Spider):
    ...

class SpiderB(Spider):
    ...

async def start():
    await asyncio.gather(SpiderA.async_start(), SpiderB.async_start())

asyncio.run(start())
```

这样运行时会有下面这样的报错：

```
[2020:04:25 22:13:52] ERROR asyncio Exception in callback <TaskWakeupMethWrapper object at 0x7f2a98693ad0>
handle: <Handle <TaskWakeupMethWrapper object at 0x7f2a98693ad0>>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/lib/python3.7/asyncio/tasks.py", line 651, in cancel
    if child.cancel():
  File "/usr/lib/python3.7/asyncio/tasks.py", line 651, in cancel
    if child.cancel():
  File "/usr/lib/python3.7/asyncio/tasks.py", line 651, in cancel
    if child.cancel():
  [Previous line repeated 246 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

(按理解，我觉得就是两个task并发执行，我确实也试过如果直接单个await Spider.async_start()作为协程顺序运行两个Spider，是没有问题的)对此表示没有明白，这个是使用框架的方式不对吗？

对这个知识实在有限，很希望您能帮忙解答下这样的问题。。

**Comment by howie6879** [comment]
@Vastxiao 

抱歉，回复晚了，可以解决的：

以豆瓣为例：

```python
#!/usr/bin/env python

from ruia import AttrField, Item, Spider, TextField


class DoubanItem(Item):
    target_item = TextField(css_select="div.item")
    title = TextField(css_select="span.title")
    cover = AttrField(css_select="div.pic>a>img", attr="src")
    abstract = TextField(css_select="span.inq", default="")

    async def clean_title(self, title):
        if isinstance(title, str):
            return title
        else:
            return "".join([i.text.strip().replace("\xa0", "") for i in title])


class DoubanSpider(Spider):
    name = "DoubanSpider"
    start_urls = ["https://movie.douban.com/top250"]
    request_config = {"RETRIES": 3, "DELAY": 0, "TIMEOUT": 20}
    concurrency = 10
    # aiohttp config
    aiohttp_kwargs = {}

    async def parse(self, response):
        etree = response.html_etree
        pages = ["?start=0&filter="] + [
            i.get("href") for i in etree.cssselect(".paginator>a")
        ]
        for index, page in enumerate(pages):
            url = self.start_urls[0] + page
            yield self.request(
                url=url, metadata={"index": index}, callback=self.parse_item
            )

    async def parse_item(self, response):
        async for item in DoubanItem.get_items(html=response.html):
            yield item

    async def process_item(self, item: DoubanItem):
        self.logger.info(item)


if __name__ == "__main__":
    # DoubanSpider.start()
    import asyncio

    async def start():
        await asyncio.gather(
            DoubanSpider.async_start(cancel_tasks=False),
            DoubanSpider.async_start(cancel_tasks=False),
        )

    asyncio.get_event_loop().run_until_complete(start())
```
